import{i as n}from"./assets/bi_x-octagon-ddd250c8.js";/* empty css                      */import{i as o}from"./assets/vendor-77e16229.js";const c="/goit-js-hw-10/assets/bi_bell-28eb2f9b.svg",a="/goit-js-hw-10/assets/bi_check2-circle-286069d5.svg",f="/goit-js-hw-10/assets/bi_exclamation-triangle-abfc0c5e.svg",u=document.querySelector(".form"),i=document.querySelector("[name=delay]");document.querySelector("[name=state]");const l=document.querySelector("fieldset");document.querySelector("button");const d=document.querySelector(".lable-delay"),m=document.querySelector(".lable-state");i.style.cssText=`border: 1px solid #808080;
border-radius: 4px;
width: 360px;
height: 40px;
font-weight: 400;
font-size: 16px;
line-height: 1.5;
letter-spacing: 0.04em;
color: #2e2f42;`;m.style.cssText=`font-weight: 400;
font-size: 16px;
line-height: 1.5;
color: #2e2f42;`;l.style.cssText=`border-radius: 4px;
stroke-width: 1px;
stroke: #808080;
width: 360px;
height: 64px;
display: flex;
align-items: center;
justify-content: center;
flex-direction: row;
gap: 48px;
padding: 0px;
margin-left: 40px;`;d.style.cssText=`display: flex;
    margin-bottom: 16px;
    margin-top: 40px;
    font-size: 16px;
     flex-direction: column;
     margin-left: 40px`;o.info({title:"Hallo!",message:"Wellcome!",position:"topRight",backgroundColor:"#09f",messageColor:"#fff",titleColor:"#fff",iconUrl:`${c}`});u.addEventListener("submit",function(r){r.preventDefault();const t=parseInt(i.value,10);if(isNaN(t)){o.error({title:"Caution",message:"You forgot important data",position:"topRight",messageColor:"#fff",backgroundColor:"#ffa000",titleColor:"#fff",iconUrl:`${f}`});return}new Promise((e,s)=>{setTimeout(()=>{l.querySelector('input[type="radio"]:checked').value==="fulfilled"?e(`Fulfilled promise in ${t}ms`):s(`Rejected promise in ${t}ms`)},t)}).then(e=>{o.success({title:"OK",message:e,position:"topRight",backgroundColor:"#59a10d",messageColor:"#fff",titleColor:"#fff",iconUrl:`${a}`})}).catch(e=>{o.error({title:"Error",message:e,position:"topRight",backgroundColor:"#ef4040",messageColor:"#fff",titleColor:"#fff",iconUrl:`${n}`})}).finally(()=>{i.value="",document.querySelector('input[value="fulfilled"]').checked=!1,document.querySelector('input[value="rejected"]').checked=!1})});
//# sourceMappingURL=commonHelpers2.js.map
