import"./assets/modulepreload-polyfill-3cfb730f.js";/* empty css                      */import{i as o}from"./assets/vendor-77e16229.js";const r=document.querySelector(".form"),i=document.querySelector("[name=delay]"),s=document.querySelector("[name=state]"),c=document.querySelector("fieldset");document.querySelector("button");const a=document.querySelector(".lable-delay"),p=document.querySelector(".lable-state");i.style.cssText=`border: 1px solid #808080;
border-radius: 4px;
width: 360px;
height: 40px;
font-weight: 400;
font-size: 16px;
line-height: 1.5;
letter-spacing: 0.04em;
color: #2e2f42;`;p.style.cssText=`font-weight: 400;
font-size: 16px;
line-height: 1.5;
color: #2e2f42;`;c.style.cssText=`border-radius: 4px;
stroke-width: 1px;
stroke: #808080;
width: 360px;
height: 64px;
display: flex;
align-items: center;
justify-content: center;
flex-direction: row;
gap: 48px;
padding: 0px;
margin-left: 40px;`;a.style.cssText=`display: flex;
    margin-bottom: 16px;
    margin-top: 40px;
    font-size: 16px;
     flex-direction: column;
     margin-left: 40px`;o.info({title:"Hallo!",message:"Wellcome!",position:"topRight"});r.addEventListener("submit",function(l){l.preventDefault();const t=parseInt(i.value,10);new Promise((e,n)=>{setTimeout(()=>{s.checked?e(`✅ Fulfilled promise in ${t}ms`):n(`❌ Rejected promise in ${t}ms`)},t)}).then(e=>{o.success({title:"Success",message:e,position:"topRight"})}).catch(e=>{o.error({title:"Error",message:e,position:"topRight"})}).finally(()=>{i.value="",s.checked=!1})});
//# sourceMappingURL=commonHelpers2.js.map
